### ISSUE TITLE
"No module named pip" error on push to heroku

### ISSUE THREAD

**Issue by lovesh** [getpelican/heroku-buildpack-pelican#9]
When i push to heroku the push gets rejected with this error message
```
-----> Fetching custom git buildpack... done
-----> Pelican app detected
-----> Installing Python (python-3.4.2)
-----> Ensure pip
Ignoring ensurepip failure: pip 1.5.6 requires SSL/TLS
-----> Installing Pelican
/app/tmp/cache/python-3.4.2/bin/python: No module named pip

 !     Push rejected, failed to compile Pelican app
```

**Comment by AdamWagner** [comment]
+1

Also having this issue. Many Google searches and attempts later, and can't find a way around this one. Does the buildpack need updated?

**Comment by atkailash** [comment]
I figured out the problem, at least for me. My app stack was set for Cedar-14 automatically, but it seems the buildpack is set for cedar. When the stack for the application is set to cedar (`heroku stack:set cedar <appname>`), it works fine. I'm trying to figure out how to fix it right now, but can't find a whole lot of helpful documentation to see specifically

**Comment by atkailash** [comment]
Well, that was simple! Changed the variable in "build" to "cedar-14" and worked just fine. Submitting pull request now.
